#!/usr/bin/env zsh

setopt errexit
setopt localtraps
set -uo pipefail

_dev-zinve-source() {
    if [[ -e ${1} ]]; then
        echo "sourcing '$1'" >&2 ;
        . ${1}
    else
        echo "ERROR: SOURCE TARGET '$1' NOT FOUND!" >&2 ;
        exit 1 ;
    fi
}

if [[ ${ZINVE__CONFIG__IS_PROD_BUNDLE:-""} != "1" ]]; then
    _dev-zinve-source ${0:A:h}/misc/dev-prelude.zsh
    _dev-zinve-source ${0:A:h}/lib-loader.zsh
    zinve::loader::load-all-libs ;
fi

zinve-main-dispatch $@

